# -*- coding: utf-8 -*-
"""google_colab_llm_offload_fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxMxPadctgr0nYlUFSpJfC4odFOaTboL

# 🚀 Google Colab LLM Offload for Banking Assistant

This notebook will:
1. Install and configure Ollama in Colab
2. Mount Google Drive to access your GGUF model
3. Create dynamic Modelfile and register your model
4. Start Ollama server with ngrok exposure
5. Generate public ngrok URL for your local FastAPI

**Your local FastAPI backend remains unchanged** — only the `OLLAMA_BASE_URL` environment variable will point to Colab!

---
### 📋 Prerequisites
- Your GGUF model file should be uploaded to Google Drive
- Local FastAPI continues running normally
- No changes needed to your existing backend code

## 🔧 Step 1: Install Dependencies and Mount Drive
"""

!pip install -q pyngrok

from google.colab import drive
drive.mount('/content/drive')

print('✅ Google Drive mounted successfully!')
print('📁 Drive path: /content/drive/MyDrive')

"""## 📦 Step 2: Setup Model Path and Variables"""

import os, subprocess, time, requests

# ────────────────────────────────────────────────────────────
# ✏️  EDIT THESE
BANKING_MODEL_FILENAME   = 'gemma-2b-banking-q4_k_m.gguf'
MARKETING_MODEL_FILENAME = 'gemma-2b-sales-agent-Q4_K_M.gguf'
NGROK_AUTH_TOKEN         = '3BAvo7pdnsT4QOxCgaaQ3RVUt0Q_7fKngxaiUmR6ExxqTock7'  # ✏️
# ────────────────────────────────────────────────────────────

DRIVE_PATH           = '/content/drive/MyDrive'
BANKING_MODEL_PATH   = f'{DRIVE_PATH}/{BANKING_MODEL_FILENAME}'
MARKETING_MODEL_PATH = f'{DRIVE_PATH}/{MARKETING_MODEL_FILENAME}'
OLLAMA_PORT          = 11434

all_ok = True
for label, path in [('Banking', BANKING_MODEL_PATH), ('Marketing', MARKETING_MODEL_PATH)]:
    if os.path.exists(path):
        size_gb = os.path.getsize(path) / (1024**3)
        print(f'✅ {label} model found: {os.path.basename(path)} ({size_gb:.2f} GB)')
    else:
        print(f'❌ {label} model NOT found: {path}')
        all_ok = False

print()
print('✅ Both models located — ready to proceed!' if all_ok else '⚠️  Fix missing models above before continuing.')

!sudo apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh
print("✅ Ollama installed correctly!")

"""## 🚀 Step 4: Start Ollama Server and Load Model"""

import subprocess, time, os, requests

os.system('pkill -f ollama || true')
time.sleep(2)

env = os.environ.copy()
env['OLLAMA_HOST'] = '0.0.0.0'

ollama_process = subprocess.Popen(
    ['ollama', 'serve'],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
    env=env
)

print('⏳ Waiting for Ollama server to start...')
time.sleep(8)

try:
    r = requests.get('http://localhost:11434/api/tags', timeout=5)
    print('✅ Ollama server is running!')
except Exception as e:
    print(f'❌ Ollama server did not start: {e}')
    print('   Try re-running this cell.')

import subprocess

banking_modelfile = f'''FROM {BANKING_MODEL_PATH}

PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER repeat_penalty 1.1
PARAMETER num_ctx 2048
PARAMETER num_predict 150

PARAMETER stop "### Instruction:"
PARAMETER stop "<|end|>"
PARAMETER stop "</s>"

SYSTEM """You are a professional banking and sales assistant. You provide accurate,
helpful responses about banking products, account inquiries, loan applications,
and sales-related questions. Keep your responses focussed."""

TEMPLATE """### Instruction:
{{{{ .Prompt }}}}

### Response:
"""
'''

with open('/content/BankingModelfile', 'w') as f:
    f.write(banking_modelfile)

print('📄 Banking Modelfile created. Registering...')

result = subprocess.run(
    ['ollama', 'create', 'banking-model', '-f', '/content/BankingModelfile'],
    capture_output=True, text=True
)

if result.returncode == 0:
    print('✅ Banking model registered as banking-model:latest!')
else:
    print('❌ Error:')
    print(result.stderr)

marketing_modelfile = f'''FROM {MARKETING_MODEL_PATH}

PARAMETER temperature 0.6
PARAMETER num_predict 800
PARAMETER num_ctx 1024
PARAMETER stop "<start_of_turn>"
PARAMETER stop "<end_of_turn>"

SYSTEM """
You are a professional outbound marketing agent. You create engaging sales pitches and marketing content based on the business details provided. Always use only the information given about the business - never invent fake discounts, offers, or details. Be conversational, persuasive, and customer-focused.
"""
'''

with open('/content/MarketingModelfile', 'w') as f:
    f.write(marketing_modelfile)

print('📄 Marketing Modelfile created. Registering...')

result = subprocess.run(
    ['ollama', 'create', 'gemma-sales-agent', '-f', '/content/MarketingModelfile'],
    capture_output=True, text=True
)

if result.returncode == 0:
    print('✅ Marketing model registered as gemma-sales-agent:latest!')
else:
    print('❌ Error:')
    print(result.stderr)

import requests

r = requests.get('http://localhost:11434/api/tags', timeout=5)
models = r.json().get('models', [])
names  = [m['name'] for m in models]

print(f'📦 {len(models)} model(s) registered in Ollama:')
for n in names:
    print(f'   • {n}')

banking_ok   = any('banking-model'     in n for n in names)
marketing_ok = any('gemma-sales-agent' in n for n in names)

print()
print('🏦 banking-model:    ', '✅' if banking_ok   else '❌ NOT FOUND — re-run Step 5')
print('📣 gemma-sales-agent:', '✅' if marketing_ok else '❌ NOT FOUND — re-run Step 6')

"""## 🌐 Step 5: Setup Ngrok Tunnel"""

from pyngrok import ngrok
import time

ngrok.set_auth_token(NGROK_AUTH_TOKEN)
ngrok.kill()
time.sleep(2)

# One tunnel — both models share the same Ollama instance on port 11434.
# Select the model per request via the 'model' field in the JSON body.
try:
    tunnel    = ngrok.connect(11434, bind_tls=True)
    ngrok_url = tunnel.public_url
    print('✅ Ngrok tunnel created!')
    print(f'🔗 Public Ollama URL: {ngrok_url}')
    print()
    print('Both models are accessible through this single URL:')
    print(f'  Banking   → POST {ngrok_url}/api/generate  [model: "banking-model"]')
    print(f'  Marketing → POST {ngrok_url}/api/generate  [model: "gemma-sales-agent"]')
except Exception as e:
    print(f'❌ Ngrok error: {e}')
    ngrok_url = None