"""
Intent Detection Configuration Module

This module contains all rule-based configurations for banking intent detection:
- Intent relationships (semantic co-occurrence)
- Critical keyword overrides (safety net for high-priority intents)
- Suppression rules (contextual filtering)
- Soft keyword hints (confidence boosting)
- Intent priority/severity mapping
- Intent label mappings
"""

# Intent relationships: If primary intent is detected, also suggest related intents
# Maps intent → list of semantically related intents that often co-occur
INTENT_RELATIONSHIPS = {
    'card_arrival': ['card_not_working', 'card_acceptance', 'activate_my_card', 'card_linking'],
    'card_not_working': ['card_swallowed', 'declined_card_payment', 'card_payment_not_recognised', 'contactless_not_working', 'activate_my_card', 'card_linking'],
    'declined_cash_withdrawal': ['card_swallowed', 'card_not_working', 'cash_withdrawal_charge', 'pin_blocked', 'passcode_forgotten'],
    'card_swallowed': ['card_not_working', 'declined_cash_withdrawal', 'declined_card_payment', 'lost_or_stolen_card', 'get_physical_card'],
    'card_payment_wrong_exchange_rate': ['extra_charge_on_statement', 'pending_card_payment', 'exchange_rate', 'exchange_charge', 'request_refund'],
    'pending_card_payment': ['card_payment_not_recognised', 'extra_charge_on_statement', 'request_refund', 'card_payment_wrong_exchange_rate'],
    'extra_charge_on_statement': ['pending_card_payment', 'card_payment_wrong_exchange_rate', 'card_payment_fee_charged', 'card_payment_not_recognised', 'request_refund'],
    'verify_source_of_funds': ['unable_to_verify_identity', 'verify_my_identity', 'why_verify_identity'],
    'request_refund': ['Refund_not_showing_up', 'card_payment_not_recognised', 'reverted_card_payment?', 'extra_charge_on_statement', 'transaction_charged_twice'],
    'declined_card_payment': ['card_not_working', 'card_swallowed', 'declined_cash_withdrawal', 'contactless_not_working', 'pin_blocked'],
    'failed_transfer': ['declined_transfer', 'transfer_not_received_by_recipient', 'balance_not_updated_after_bank_transfer', 'cancel_transfer', 'transfer_fee_charged'],
    'top_up_failed': ['pending_top_up', 'balance_not_updated_after_bank_transfer', 'top_up_reverted', 'top_up_by_card_charge', 'top_up_limits'],
    'compromised_card': ['lost_or_stolen_card', 'card_payment_not_recognised', 'request_refund', 'cash_withdrawal_not_recognised', 'terminate_account'],
    'lost_or_stolen_card': ['compromised_card', 'card_swallowed', 'terminate_account', 'get_physical_card', 'getting_spare_card'],
    'pin_blocked': ['passcode_forgotten', 'change_pin', 'declined_cash_withdrawal', 'declined_card_payment', 'unable_to_verify_identity'],
    'passcode_forgotten': ['pin_blocked', 'change_pin', 'unable_to_verify_identity', 'declined_cash_withdrawal'],
    'contactless_not_working': ['card_not_working', 'declined_card_payment', 'card_acceptance', 'apple_pay_or_google_pay'],
    'balance_not_updated_after_bank_transfer': ['pending_transfer', 'failed_transfer', 'transfer_timing', 'transfer_not_received_by_recipient'],
    'card_payment_not_recognised': ['compromised_card', 'request_refund', 'extra_charge_on_statement', 'pending_card_payment', 'transaction_charged_twice'],
    'cash_withdrawal_not_recognised': ['compromised_card', 'request_refund', 'wrong_amount_of_cash_received'],
    'transaction_charged_twice': ['request_refund', 'extra_charge_on_statement', 'card_payment_not_recognised'],
    'transfer_not_received_by_recipient': ['failed_transfer', 'pending_transfer', 'cancel_transfer', 'balance_not_updated_after_bank_transfer'],
    'Refund_not_showing_up': ['request_refund', 'balance_not_updated_after_bank_transfer', 'pending_card_payment', 'reverted_card_payment?'],
    'unable_to_verify_identity': ['verify_my_identity', 'verify_source_of_funds', 'why_verify_identity', 'edit_personal_details'],
    'activate_my_card': ['card_arrival', 'card_not_working', 'card_linking', 'pin_blocked'],
    'virtual_card_not_working': ['getting_virtual_card', 'card_not_working', 'declined_card_payment'],
    'apple_pay_or_google_pay': ['contactless_not_working', 'card_linking', 'card_not_working'],
    'cancel_transfer': ['failed_transfer', 'transfer_not_received_by_recipient', 'wrong_exchange_rate_for_cash_withdrawal'],
    'card_about_to_expire': ['card_arrival', 'get_physical_card', 'order_physical_card'],
    'terminate_account': ['compromised_card', 'lost_or_stolen_card', 'unable_to_verify_identity'],
    'reverted_card_payment?': ['request_refund', 'Refund_not_showing_up', 'card_payment_not_recognised'],
    'top_up_reverted': ['top_up_failed', 'balance_not_updated_after_bank_transfer', 'verify_top_up'],
    'exchange_charge': ['card_payment_wrong_exchange_rate', 'extra_charge_on_statement', 'exchange_rate'],
    'card_payment_fee_charged': ['extra_charge_on_statement', 'card_payment_wrong_exchange_rate', 'request_refund'],
    'transfer_fee_charged': ['extra_charge_on_statement', 'failed_transfer', 'request_refund'],
    'direct_debit_payment_not_recognised': ['card_payment_not_recognised', 'request_refund', 'compromised_card'],
    'pending_transfer': ['transfer_timing', 'transfer_not_received_by_recipient', 'balance_not_updated_after_bank_transfer', 'cancel_transfer'],
    'card_linking': ['activate_my_card', 'card_not_working', 'apple_pay_or_google_pay'],
    'getting_virtual_card': ['virtual_card_not_working', 'get_disposable_virtual_card'],
    'lost_or_stolen_phone': ['lost_or_stolen_card', 'apple_pay_or_google_pay', 'terminate_account'],
}

# Critical keyword overrides: always include these intents if matched (safety net)
CRITICAL_KEYWORD_OVERRIDES = {
    "card_swallowed": ["swallowed", "kept my card", "did not return my card", "atm ate", "machine retained", "card stuck", "atm kept", "didn't return", "didnt return", "atm has my card"],
    "lost_or_stolen_card": ["lost my card", "card stolen", "card missing", "can't find card", "cant find card", "stolen card", "someone took my card", "misplaced card", "card disappeared", "card lost"],
    "compromised_card": ["fraud", "unauthorized", "unauthorised", "hacked", "fraudulent", "scam", "suspicious transaction", "didn't make this payment", "didnt make this payment", "not my transaction", "phishing", "identity theft", "someone accessed", "account compromised", "breached", "unauthorized access", "suspicious activity", "not me", "wasn't me", "wasnt me"],
    "declined_card_payment": ["payment declined", "card declined", "transaction declined", "payment rejected", "card rejected", "payment refused", "transaction refused", "payment blocked"],
    "failed_transfer": ["transfer failed", "money didn't go", "payment bounced", "transfer bounced", "couldn't send money", "couldnt send", "transfer error", "money not sent", "send failed"],
    "pin_blocked": ["pin blocked", "pin locked", "too many attempts", "wrong pin too many", "locked out", "account locked", "pin frozen", "multiple wrong attempts"],
    "unable_to_verify_identity": ["identity verification failed", "cant verify", "can't verify", "verification rejected", "documents rejected", "kyc failed", "verification issues"],
    "terminate_account": ["close account", "delete account", "cancel account", "close my account", "terminate", "remove account", "deactivate account"],
}

# Suppression rules: remove low-value intents when higher-severity signals appear in text
SUPPRESSION_RULES = {
    "card_arrival": ["not working", "declined", "swallowed", "doesn't work", "blocked", "damaged", "broken", "defective"],
    "card_delivery_estimate": ["arrived", "received", "got it", "have it", "in hand"],
    "activate_my_card": ["already activated", "still not working", "activated but", "active but"],
    "card_linking": ["already linked", "linked but not working", "connected but"],
    "getting_virtual_card": ["have virtual card", "got virtual card", "already have"],
    "order_physical_card": ["already ordered", "already arrived", "received card"],
    "verify_my_identity": ["already verified", "verified before", "previously verified", "verification done"],
    "exchange_rate": ["wrong exchange rate", "incorrect rate", "overcharged", "unfair rate", "bad rate"],
    "card_about_to_expire": ["expired", "already expired", "card expired"],
    "getting_spare_card": ["have spare", "received spare", "got replacement"],
    "top_up_limits": ["limit reached", "exceeded limit", "hit limit"],
    "transfer_timing": ["not received", "didn't arrive", "still waiting", "money missing"],
    "pending_card_payment": ["completed", "processed", "went through"],
    "pending_transfer": ["completed", "received", "went through", "arrived"],
    "pending_top_up": ["completed", "received", "balance updated"],
    "age_limit": ["already signed up", "have account", "registered"],
    "country_support": ["in country", "currently here", "already here"],
}

# Soft keyword hints: boost common usability issues even if model confidence is low
SOFT_KEYWORD_HINTS = [
    {
        "intent": "card_not_working",
        "keywords": [
            "not working", "doesn't work", "doesnt work", "won't work", "wont work",
            "not accepted", "declined everywhere", "cannot pay", "can't pay", "cant pay",
            "payment failing", "payment fails", "card inactive", "card blocked", "card disabled",
            "card broken", "card damaged", "card defective", "not functioning",
        ],
        "confidence": 0.6,
    },
    {
        "intent": "request_refund",
        "keywords": [
            "get my money back", "refund me", "money back", "return my money", "give back",
            "charged incorrectly", "overcharged", "double charged", "duplicate charge",
            "charged twice", "wrong amount charged", "refund please", "reverse charge",
            "chargeback", "dispute charge", "cancel charge",
        ],
        "confidence": 0.55,
    },
    {
        "intent": "passcode_forgotten",
        "keywords": [
            "forgot pin", "forgot password", "forgot passcode", "don't remember pin",
            "dont remember pin", "can't remember pin", "cant remember", "lost my pin",
            "don't know pin", "dont know pin", "forgotten pin", "reset pin", "recover pin",
        ],
        "confidence": 0.65,
    },
    {
        "intent": "balance_not_updated_after_bank_transfer",
        "keywords": [
            "balance not updated", "money not showing", "transfer not showing",
            "where is my money", "sent money but", "paid but balance", "balance wrong",
            "funds not reflected", "payment not reflected", "balance incorrect",
        ],
        "confidence": 0.5,
    },
    {
        "intent": "contactless_not_working",
        "keywords": [
            "contactless not working", "tap not working", "tap to pay not working",
            "can't tap", "cant tap", "nfc not working", "tap declined", "contactless declined",
            "tap failed", "wave not working",
        ],
        "confidence": 0.6,
    },
    {
        "intent": "top_up_failed",
        "keywords": [
            "top up failed", "couldn't top up", "couldnt top up", "top up declined",
            "add money failed", "deposit failed", "load failed", "recharge failed",
            "can't add money", "cant add funds",
        ],
        "confidence": 0.6,
    },
    {
        "intent": "card_payment_wrong_exchange_rate",
        "keywords": [
            "wrong exchange rate", "bad exchange rate", "unfair rate", "incorrect rate",
            "poor rate", "exchange rate too high", "rate too low", "currency conversion wrong",
            "converted incorrectly", "exchange rate charged",
        ],
        "confidence": 0.55,
    },
    {
        "intent": "card_payment_not_recognised",
        "keywords": [
            "don't recognize", "dont recognize", "don't recognise", "dont recognise",
            "unknown payment", "unknown charge", "mystery charge", "what is this charge",
            "didn't buy", "didnt buy", "never purchased", "not my purchase",
        ],
        "confidence": 0.6,
    },
    {
        "intent": "transfer_not_received_by_recipient",
        "keywords": [
            "recipient didn't receive", "recipient didnt receive", "money not received",
            "didn't get money", "didnt get money", "never arrived", "not received",
            "sent but not received", "transferred but",
        ],
        "confidence": 0.55,
    },
    {
        "intent": "Refund_not_showing_up",
        "keywords": [
            "refund not showing", "refund missing", "where is refund", "no refund",
            "refund not received", "waiting for refund", "refund delayed",
        ],
        "confidence": 0.55,
    },
    {
        "intent": "apple_pay_or_google_pay",
        "keywords": [
            "apple pay not working", "google pay not working", "digital wallet",
            "mobile payment", "phone payment", "wallet app",
        ],
        "confidence": 0.5,
    },
    {
        "intent": "virtual_card_not_working",
        "keywords": [
            "virtual card not working", "digital card not working", "online card",
            "temporary card not working", "virtual card declined",
        ],
        "confidence": 0.6,
    },
    {
        "intent": "cash_withdrawal_not_recognised",
        "keywords": [
            "didn't withdraw", "didnt withdraw", "never withdrew", "withdrawal not me",
            "unauthorized withdrawal", "unknown withdrawal",
        ],
        "confidence": 0.6,
    },
    {
        "intent": "card_about_to_expire",
        "keywords": [
            "card expiring", "card expires", "expiry date", "expiration date",
            "card expired", "expired card", "renew card", "about to expire",
            "going to expire", "gonna expire", "will expire", "near expiry",
            "is expired", "has expired", "just expired", "already expired",
            "card ran out", "card no longer valid", "expired what do",
        ],
        "confidence": 0.7,
    },
    {
        "intent": "cancel_transfer",
        "keywords": [
            "cancel transfer", "stop transfer", "reverse transfer", "undo transfer",
            "cancel payment", "stop payment", "wrong recipient", "sent to wrong person",
        ],
        "confidence": 0.6,
    },
]

# Intent priority/severity mapping
INTENT_PRIORITY = {
    # CRITICAL - Security & Fraud (Priority 10)
    'card_swallowed': 10,
    'compromised_card': 10,
    'lost_or_stolen_card': 10,
    'lost_or_stolen_phone': 10,
    
    # HIGH - Major Issues (Priority 9)
    'card_not_working': 9,
    'failed_transfer': 9,
    'declined_transfer': 9,
    'declined_card_payment': 9,
    'declined_cash_withdrawal': 9,
    'unable_to_verify_identity': 9,
    
    # MEDIUM-HIGH - Payment/Transaction Issues (Priority 7)
    'card_payment_fee_charged': 7,
    'card_payment_not_recognised': 7,
    'card_payment_wrong_exchange_rate': 7,
    'cash_withdrawal_charge': 7,
    'cash_withdrawal_not_recognised': 7,
    'direct_debit_payment_not_recognised': 7,
    'transfer_fee_charged': 7,
    'transfer_not_received_by_recipient': 7,
    'request_refund': 7,
    'Refund_not_showing_up': 7,
    
    # MEDIUM - Account/Card Management (Priority 5)
    'pin_blocked': 5,
    'passcode_forgotten': 5,
    'change_pin': 5,
    'contactless_not_working': 5,
    'virtual_card_not_working': 5,
    'cancel_transfer': 5,
    'terminate_account': 5,
    
    # LOW-MEDIUM - Transactions & Features (Priority 3)
    'pending_transfer': 3,
    'pending_card_payment': 3,
    'pending_cash_withdrawal': 3,
    'pending_top_up': 3,
    'top_up_failed': 3,
    'balance_not_updated_after_bank_transfer': 3,
    'balance_not_updated_after_cheque_or_cash_deposit': 3,
    
    # LOW - Info & Routine Operations (Priority 1)
    'card_arrival': 1,
    'card_about_to_expire': 1,
    'card_acceptance': 1,
    'card_delivery_estimate': 1,
    'card_linking': 1,
    'activate_my_card': 1,
    'getting_virtual_card': 1,
    'get_physical_card': 1,
    'getting_spare_card': 1,
    'get_disposable_virtual_card': 1,
    'order_physical_card': 1,
    'age_limit': 1,
    'apple_pay_or_google_pay': 1,
    'atm_support': 1,
    'beneficiary_not_allowed': 1,
    'country_support': 1,
    'exchange_charge': 1,
    'exchange_rate': 1,
    'exchange_via_app': 1,
    'extra_charge_on_statement': 1,
    'fiat_currency_support': 1,
    'receiving_money': 1,
    'supported_cards_and_currencies': 1,
    'top_up_by_bank_transfer_charge': 1,
    'top_up_by_card_charge': 1,
    'top_up_by_cash_or_cheque': 1,
    'top_up_limits': 1,
    'top_up_reverted': 1,
    'topping_up_by_card': 1,
    'transfer_timing': 1,
    'transfer_into_account': 1,
    'verify_my_identity': 1,
    'verify_top_up': 1,
    'verify_source_of_funds': 1,
    'visa_or_mastercard': 1,
    'why_verify_identity': 1,
    'disposable_card_limits': 1,
    'edit_personal_details': 1,
    'automatic_top_up': 1,
    'reverted_card_payment?': 1,
    'transaction_charged_twice': 1,
    'wrong_amount_of_cash_received': 1,
    'wrong_exchange_rate_for_cash_withdrawal': 1,
}

# Intent label to name mapping (model output)
INTENT_CLASSES = {
    0: 'activate_my_card',
    1: 'age_limit',
    2: 'apple_pay_or_google_pay',
    3: 'atm_support',
    4: 'automatic_top_up',
    5: 'balance_not_updated_after_bank_transfer',
    6: 'balance_not_updated_after_cheque_or_cash_deposit',
    7: 'beneficiary_not_allowed',
    8: 'cancel_transfer',
    9: 'card_about_to_expire',
    10: 'card_acceptance',
    11: 'card_arrival',
    12: 'card_delivery_estimate',
    13: 'card_linking',
    14: 'card_not_working',
    15: 'card_payment_fee_charged',
    16: 'card_payment_not_recognised',
    17: 'card_payment_wrong_exchange_rate',
    18: 'card_swallowed',
    19: 'cash_withdrawal_charge',
    20: 'cash_withdrawal_not_recognised',
    21: 'change_pin',
    22: 'compromised_card',
    23: 'contactless_not_working',
    24: 'country_support',
    25: 'declined_card_payment',
    26: 'declined_cash_withdrawal',
    27: 'declined_transfer',
    28: 'direct_debit_payment_not_recognised',
    29: 'disposable_card_limits',
    30: 'edit_personal_details',
    31: 'exchange_charge',
    32: 'exchange_rate',
    33: 'exchange_via_app',
    34: 'extra_charge_on_statement',
    35: 'failed_transfer',
    36: 'fiat_currency_support',
    37: 'get_disposable_virtual_card',
    38: 'get_physical_card',
    39: 'getting_spare_card',
    40: 'getting_virtual_card',
    41: 'lost_or_stolen_card',
    42: 'lost_or_stolen_phone',
    43: 'order_physical_card',
    44: 'passcode_forgotten',
    45: 'pending_card_payment',
    46: 'pending_cash_withdrawal',
    47: 'pending_top_up',
    48: 'pending_transfer',
    49: 'pin_blocked',
    50: 'receiving_money',
    51: 'Refund_not_showing_up',
    52: 'request_refund',
    53: 'reverted_card_payment?',
    54: 'supported_cards_and_currencies',
    55: 'terminate_account',
    56: 'top_up_by_bank_transfer_charge',
    57: 'top_up_by_card_charge',
    58: 'top_up_by_cash_or_cheque',
    59: 'top_up_failed',
    60: 'top_up_limits',
    61: 'top_up_reverted',
    62: 'topping_up_by_card',
    63: 'transaction_charged_twice',
    64: 'transfer_fee_charged',
    65: 'transfer_into_account',
    66: 'transfer_not_received_by_recipient',
    67: 'transfer_timing',
    68: 'unable_to_verify_identity',
    69: 'verify_my_identity',
    70: 'verify_source_of_funds',
    71: 'verify_top_up',
    72: 'virtual_card_not_working',
    73: 'visa_or_mastercard',
    74: 'why_verify_identity',
    75: 'wrong_amount_of_cash_received',
    76: 'wrong_exchange_rate_for_cash_withdrawal'
}
